sudo: required

language: erlang

services:
  - docker

before_install:
- docker pull resin/rpi-raspbian
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
- echo test